### ISSUE TITLE
FYI - Helm chart

### ISSUE THREAD

**Issue by egeland** [mumoshu/kube-spot-termination-notice-handler#7]
Hi,

I have just submitted a simple Helm chart for this - just to make things easier.
https://github.com/kubernetes/charts/pull/1908

Cheers,
Frode

**Comment by egeland** [comment]
I've added this to the README in #8 as well.

**Comment by christopherhein** [comment]
Does this support RBAC based clusters @egeland or is it not necessary for connecting back into the apiserver…

**Comment by egeland** [comment]
Please note this project has moved to https://github.com/kube-aws/kube-spot-termination-notice-handler
